Division codigo en modulos
asus753/js-intermedio pull request #4
Opened 2020-02-19 03:17 UTC by asus753

2020-03-15 21:09 UTC, fsodano commented on clase-12/tarea/tarea-pokeAPI/src/index.js
> +let CantidadTotalPokemons
cantidadTotalPokemons

2020-03-15 21:10 UTC, fsodano commented on clase-12/tarea/tarea-pokeAPI/src/index.js
> +async function clickCarta () {
por qué esta función es async? Y además, clickCarta me da a entender que le estás haciendo click a una carta... en realidad debería llamarse `definirManejadorClickCarta` o algo similar a eso

2020-03-15 21:13 UTC, fsodano commented on clase-12/tarea/tarea-pokeAPI/src/index.js
> +  if (testURLdañada(URLanterior, URLsiguiente)) {
qué hace testURLDañada? (no le pongas ñ a las variables ni funciones, de paso)

2020-03-15 21:14 UTC, fsodano requested changes
la división está bien y el código está bastante claro, fijate por favor que todo esté en camelCase y no PascalCase y avisame y lo chusmeo otra vez!

2020-03-15 21:15 UTC, fsodano commented
Ah, y las funciones tienen que tener un verbo en infinitivo adelante, siempre. Es decir "calcularSalarioAnual" y no "salarioAnual".

2020-03-19 03:55 UTC, asus753 commented on clase-12/tarea/tarea-pokeAPI/src/index.js
> +let CantidadTotalPokemons
Se me escapo ese

2020-03-20 17:15 UTC, asus753 commented on clase-12/tarea/tarea-pokeAPI/src/index.js
> +async function clickCarta () {
Ese async se me escapo :sweat_smile:

2020-03-20 17:29 UTC, asus753 commented on clase-12/tarea/tarea-pokeAPI/src/index.js
> +  if (testURLdañada(URLanterior, URLsiguiente)) {
Eso fue uno de los principales problemas que tuve con la pokedex. Yo coloque 40 pokemons por pag, y en total son 964. Cuestión al llegar a la ultima pagina únicamente muestra 4 pokemons, eso esta bien, pero el problema surge cuando queres volver para la pagina anterior. Esa ultima pagina me devolvía una URLprevious con un limit=4 y me empezaba a mostrar solamente 4 pokemons por pagina.
Lo que hice fue que antes de cargar la URL, pase por un test que verificara el limit, si no lo pasa. llama a una función que devuelve la url ya corregida.

2020-04-25 19:38 UTC, merged